# config/packages/lexik_jwt_authentication.yaml
lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%' # Utilisez une clé secrète sécurisée
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%' # Utilisez une clé publique pour vérifier les tokens côté client
    pass_phrase: '%env(JWT_PASSPHRASE)%' # Mot de passe pour déchiffrer la clé privée (si applicable)
    token_ttl: 3600 # Durée de vie du token en secondes (ici, 1 heure)
